name: appimage-release
on:
  push:
    tags:
      - 'v*'
jobs:
  appimage:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: build appimage
        run: |
          export ACTION_MODE=true
          cd appimage
          docker-compose up

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: deepin-calculator.AppImage
          path: ./appimage/deepin-calculator/build/deepin-calculator.AppImage

      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./appimage/deepin-calculator/build/deepin-calculator.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}