name: appimage-release
on:
  push:
    branches: [ main ]
jobs:
  appimage:
    runs-on: ubuntu-20.04

    steps:
      - name: build appimage
        run: |
          pwd
          ls -al
          cd appimage
          docker-compose up
      - uses: actions/upload-artifact@v3
        with:
          name: deepin-calculator.AppImage
          path: ./appimage/deepin-calculator.AppImage
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "./appimage/deepin-calculator.AppImage"
          token: ${{ secrets.GITHUB_TOKEN }}